services:
  web:
    build: ../../servers/django-api-with-graph
    ports:
      - 8000:8000
    networks:
      - webapp

  proxy:
    build: ../../gateways/nginx
    ports:
      - 80:80
    networks:
      - webapp
    depends_on:
      - web

networks:
  webapp:
    driver: bridge
